# This is a config for E2B sandbox template.
# You can use template ID (yhfymne5c2olb6l1t55q) or template name (bolt-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("bolt-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("bolt-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('bolt-nextjs-test')

team_id = "83c403b1-99af-4fed-99f2-fdc4a0567415"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "bolt-nextjs-test"
template_id = "yhfymne5c2olb6l1t55q"
