# This is a config for E2B sandbox template.
# You can use template ID (mplswvf1qsqbiple6ajs) or template name (bolt-dev) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("bolt-dev") # Sync sandbox
# sandbox = await AsyncSandbox.create("bolt-dev") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('bolt-dev')

team_id = "83c403b1-99af-4fed-99f2-fdc4a0567415"
dockerfile = "e2b.Dockerfile"
template_name = "bolt-dev"
template_id = "mplswvf1qsqbiple6ajs"
